#!/bin/bash

TARGET_SYSTEM=$1
BUILD_TYPE=$2
BUILD_DIR_PREFIX=build

echo $TARGET_SYSTEM
echo $BUILD_TYPE

BUILD_DIR=$BUILD_DIR_PREFIX-$TARGET_SYSTEM-$BUILD_TYPE
mkdir -p $BUILD_DIR
cd $BUILD_DIR

cmake -DBUILD_SYSTEM=$TARGET_SYSTEM -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
make -j7



